spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emp?useSSL=false&serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kfm.ajax.entity
  configuration:
        map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
logging:
  level:
    org.springframework:  warn
    com.kfm.ajax: debug
