spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kfm
    username: root
    password:
  mail:
    username: 3291301890@qq.com  #???????????????
    password: hdmmeofyesgedaea   #???????????
    host: smtp.qq.com
  redis: # ??redis???
    host: 116.204.25.131 # redis?????
    username:  # redis??????
    password: qwerpoiu # redis?????
    port: 6379 # redis???????
    database: 2 # redis?????????0?
#  mvc:
#    static-path-pattern: /static/avatar/**
#    # ??????
#  web:
#    resources:
#      static-locations: file:D:/upload/avatar/
mybatis:
  configuration:
    #   ??????
    map-underscore-to-camel-case: true
    cache-enabled: true
  # ??????
  type-aliases-package: com.sign.entity
  # ??????(????????)
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
logging:
  level:
    org.springframework: warn
    com.sign: debug
interceptor:
  login_count: 5 # 5????????
  request_count: 5 # 10s???5?
  request_time: 10 # 10s
ali_sms:
  ak_id: LTAI5tAFExmv91br2NwConAZ # ????ak
  ak_secret: qOL1oEzfWEkJpg6i3ApYSX3BbFwwyF # ????ak_secret
  sign_name: YYachne # ????
  template_code: SMS_463776216 # ????
  admin_phone: 15129730812 # ??????????


